name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# --- THIS IS THE FIX ---
# Add a filter to ONLY find stable tags (e.g., v1.2.3)
# This will ignore all pre-release tags (e.g., v1.2.3-dev.SHA)
tag-filter: 'v[0-9]*.[0-9]*.[0-9]*'

version-resolver:
  major:
    labels:
      - 'Major'
  minor:
    labels:
      - 'Enhancement'
  patch:
    labels:
      - 'Bug'
  default: patch
categories:
  - title: "🚀 Enhancements"
    labels:
      - Enhancement
  - title: "🐛 Bug Fixes"
    labels:
      - Bug
exclude-labels:
  - skip-release
change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "- No changes"
template: |
  ## Changes
  $CHANGES
