name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# --- FIXED: Escaped the dots (\.) and enforced at least one digit (+) ---
# This filter now STRICTLY matches stable vX.Y.Z tags and ignores anything with -dev
tag-filter: 'v\d+\.\d+\.\d+'

version-resolver:
  major:
    labels:
      - 'Major'
  minor:
    labels:
      - 'Enhancement'
  patch:
    labels:
      - 'Bug'
  default: patch
categories:
  - title: "🚀 Enhancements"
    labels:
      - Enhancement
  - title: "🐛 Bug Fixes"
    labels:
      - Bug
exclude-labels:
  - skip-release
change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "- No changes"
template: |
  ## Changes
  $CHANGES
